import { Account, Transaction, Budget, Goal, Debt, AIRecommendation, Notification } from '@/types/finance';

// Sample Accounts
export const sampleAccounts: Account[] = [
  {
    id: 'acc_1',
    name: 'Primary Checking',
    type: 'checking',
    balance: 8456.32,
    currency: 'USD',
    institution: 'Chase Bank',
    isManual: false,
    color: '#3B82F6',
    icon: '🏦',
  },
  {
    id: 'acc_2',
    name: 'High-Yield Savings',
    type: 'savings',
    balance: 25000.00,
    currency: 'USD',
    institution: 'Marcus',
    isManual: false,
    color: '#10B981',
    icon: '💰',
  },
  {
    id: 'acc_3',
    name: 'Emergency Fund',
    type: 'savings',
    balance: 15000.00,
    currency: 'USD',
    institution: 'Ally Bank',
    isManual: true,
    color: '#F59E0B',
    icon: '🛡️',
  },
  {
    id: 'acc_4',
    name: 'Investment Portfolio',
    type: 'investment',
    balance: 87500.00,
    currency: 'USD',
    institution: 'Fidelity',
    isManual: false,
    color: '#8B5CF6',
    icon: '📈',
  },
  {
    id: 'acc_5',
    name: 'Credit Card',
    type: 'credit',
    balance: -2345.67,
    currency: 'USD',
    institution: 'Capital One',
    isManual: false,
    color: '#EF4444',
    icon: '💳',
  },
  {
    id: 'acc_6',
    name: 'Crypto Wallet',
    type: 'crypto',
    balance: 5420.00,
    currency: 'USD',
    institution: 'Coinbase',
    isManual: true,
    color: '#F97316',
    icon: '₿',
  },
];

// Sample Transactions
const now = new Date();
export const sampleTransactions: Transaction[] = [
  {
    id: 'tx_1',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1),
    amount: 5500,
    currency: 'USD',
    description: 'Monthly Salary',
    category: 'salary',
    type: 'income',
    isRecurring: true,
    merchant: 'TechCorp Inc',
  },
  {
    id: 'tx_2',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2),
    amount: -1850,
    currency: 'USD',
    description: 'Rent Payment',
    category: 'rent',
    type: 'expense',
    isRecurring: true,
    merchant: 'Skyline Apartments',
  },
  {
    id: 'tx_3',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2),
    amount: -142.35,
    currency: 'USD',
    description: 'Grocery Shopping',
    category: 'groceries',
    type: 'expense',
    isRecurring: false,
    merchant: 'Whole Foods',
  },
  {
    id: 'tx_4',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3),
    amount: -65.00,
    currency: 'USD',
    description: 'Gym Membership',
    category: 'gym',
    type: 'expense',
    isRecurring: true,
    merchant: 'Planet Fitness',
  },
  {
    id: 'tx_5',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 3),
    amount: -85.47,
    currency: 'USD',
    description: 'Electric Bill',
    category: 'utilities',
    type: 'expense',
    isRecurring: true,
    merchant: 'ConEdison',
  },
  {
    id: 'tx_6',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 4),
    amount: -34.99,
    currency: 'USD',
    description: 'Netflix + Spotify',
    category: 'subscriptions',
    type: 'expense',
    isRecurring: true,
    merchant: 'Streaming Services',
  },
  {
    id: 'tx_7',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 5),
    amount: -78.50,
    currency: 'USD',
    description: 'Dinner with friends',
    category: 'restaurants',
    type: 'expense',
    isRecurring: false,
    merchant: 'The Capital Grille',
  },
  {
    id: 'tx_8',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 6),
    amount: 850,
    currency: 'USD',
    description: 'Freelance Project Payment',
    category: 'freelance',
    type: 'income',
    isRecurring: false,
    merchant: 'Client XYZ',
  },
  {
    id: 'tx_9',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 7),
    amount: -245.00,
    currency: 'USD',
    description: 'New Running Shoes',
    category: 'clothing',
    type: 'expense',
    isRecurring: false,
    merchant: 'Nike',
  },
  {
    id: 'tx_10',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 8),
    amount: -500,
    currency: 'USD',
    description: 'Transfer to Savings',
    category: 'other',
    type: 'transfer',
    isRecurring: true,
  },
  {
    id: 'tx_11',
    accountId: 'acc_5',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 9),
    amount: -12.50,
    currency: 'USD',
    description: 'Coffee',
    category: 'coffee',
    type: 'expense',
    isRecurring: false,
    merchant: 'Starbucks',
  },
  {
    id: 'tx_12',
    accountId: 'acc_1',
    date: new Date(now.getFullYear(), now.getMonth(), now.getDate() - 10),
    amount: -45.00,
    currency: 'USD',
    description: 'Uber rides',
    category: 'rideshare',
    type: 'expense',
    isRecurring: false,
    merchant: 'Uber',
  },
];

// Sample Budgets
export const sampleBudgets: Budget[] = [
  {
    id: 'budget_1',
    name: 'Housing',
    amount: 2000,
    spent: 1935.47,
    period: 'monthly',
    categoryId: 'rent',
    rollover: false,
    alerts: { at50: false, at75: true, at90: true, atLimit: true },
  },
  {
    id: 'budget_2',
    name: 'Groceries',
    amount: 500,
    spent: 342.35,
    period: 'monthly',
    categoryId: 'groceries',
    rollover: true,
    alerts: { at50: false, at75: true, at90: true, atLimit: true },
  },
  {
    id: 'budget_3',
    name: 'Dining Out',
    amount: 300,
    spent: 178.50,
    period: 'monthly',
    categoryId: 'restaurants',
    rollover: false,
    alerts: { at50: true, at75: true, at90: true, atLimit: true },
  },
  {
    id: 'budget_4',
    name: 'Transportation',
    amount: 400,
    spent: 245.00,
    period: 'monthly',
    categoryId: 'public_transit',
    rollover: false,
    alerts: { at50: false, at75: true, at90: true, atLimit: true },
  },
  {
    id: 'budget_5',
    name: 'Entertainment',
    amount: 200,
    spent: 134.99,
    period: 'monthly',
    categoryId: 'entertainment',
    rollover: true,
    alerts: { at50: false, at75: true, at90: true, atLimit: true },
  },
  {
    id: 'budget_6',
    name: 'Shopping',
    amount: 300,
    spent: 245.00,
    period: 'monthly',
    categoryId: 'clothing',
    rollover: false,
    alerts: { at50: true, at75: true, at90: true, atLimit: true },
  },
];

// Sample Goals
export const sampleGoals: Goal[] = [
  {
    id: 'goal_1',
    name: 'Emergency Fund',
    targetAmount: 18000,
    currentAmount: 15000,
    deadline: new Date(now.getFullYear(), now.getMonth() + 6, 1),
    icon: '🛡️',
    color: '#F59E0B',
    type: 'savings',
    priority: 'high',
    autoContribute: { amount: 500, frequency: 'monthly' },
  },
  {
    id: 'goal_2',
    name: 'Vacation to Japan',
    targetAmount: 5000,
    currentAmount: 2800,
    deadline: new Date(now.getFullYear() + 1, 3, 1),
    icon: '🗾',
    color: '#EC4899',
    type: 'savings',
    priority: 'medium',
    autoContribute: { amount: 200, frequency: 'monthly' },
  },
  {
    id: 'goal_3',
    name: 'New MacBook Pro',
    targetAmount: 3000,
    currentAmount: 1200,
    deadline: new Date(now.getFullYear(), now.getMonth() + 4, 1),
    icon: '💻',
    color: '#6366F1',
    type: 'purchase',
    priority: 'low',
  },
  {
    id: 'goal_4',
    name: 'Investment Fund',
    targetAmount: 50000,
    currentAmount: 32500,
    icon: '📈',
    color: '#10B981',
    type: 'investment',
    priority: 'high',
    autoContribute: { amount: 1000, frequency: 'monthly' },
  },
];

// Sample Debts
export const sampleDebts: Debt[] = [
  {
    id: 'debt_1',
    name: 'Credit Card',
    type: 'credit_card',
    originalAmount: 5000,
    currentBalance: 2345.67,
    interestRate: 19.99,
    minimumPayment: 75,
    dueDay: 15,
    lender: 'Capital One',
    startDate: new Date(now.getFullYear() - 1, 5, 1),
  },
  {
    id: 'debt_2',
    name: 'Student Loan',
    type: 'student_loan',
    originalAmount: 35000,
    currentBalance: 22500,
    interestRate: 5.5,
    minimumPayment: 350,
    dueDay: 1,
    lender: 'Federal Student Aid',
    startDate: new Date(now.getFullYear() - 4, 8, 1),
    endDate: new Date(now.getFullYear() + 6, 8, 1),
  },
  {
    id: 'debt_3',
    name: 'Car Loan',
    type: 'auto_loan',
    originalAmount: 25000,
    currentBalance: 12800,
    interestRate: 4.5,
    minimumPayment: 450,
    dueDay: 20,
    lender: 'Toyota Financial',
    startDate: new Date(now.getFullYear() - 2, 3, 1),
    endDate: new Date(now.getFullYear() + 2, 3, 1),
  },
];

// Sample AI Recommendations
export const sampleRecommendations: AIRecommendation[] = [
  {
    id: 'rec_1',
    type: 'savings',
    title: 'Increase Emergency Fund Contribution',
    description: 'You\'re on track to reach your emergency fund goal. Consider increasing your monthly contribution to reach it faster.',
    why: 'Your current savings rate of 28% is excellent, but your emergency fund only covers 2.5 months of expenses. Financial experts recommend 3-6 months.',
    how: 'Increase your automatic transfer to your emergency fund from $500 to $750/month. You can reduce your dining budget by $100 and entertainment by $50.',
    expectedImpact: 'You\'ll reach your 6-month emergency fund goal 3 months earlier, providing better financial security.',
    risks: ['Less discretionary spending in short term', 'May need to adjust if unexpected expenses arise'],
    confidenceScore: 87,
    priority: 'high',
    actionable: true,
    actions: [
      { label: 'Adjust Budget', type: 'action', target: 'budgets' },
      { label: 'Set Up Transfer', type: 'action', target: 'goals' },
    ],
    createdAt: new Date(),
    dismissed: false,
    implemented: false,
  },
  {
    id: 'rec_2',
    type: 'debt',
    title: 'Prioritize Credit Card Payoff',
    description: 'Your credit card has a 19.99% APR. Paying it off faster could save you significant money in interest.',
    why: 'High-interest debt costs you approximately $390/year in interest alone. This money could be invested instead.',
    how: 'Use the avalanche method: after paying minimums on all debts, put extra money toward the credit card first.',
    expectedImpact: 'Paying an extra $200/month could clear this debt in 10 months instead of 36, saving ~$680 in interest.',
    risks: ['Less cash available for other goals temporarily', 'Unexpected expenses may require credit use'],
    confidenceScore: 92,
    priority: 'high',
    actionable: true,
    actions: [
      { label: 'View Debt Payoff Plan', type: 'action', target: 'debts' },
    ],
    createdAt: new Date(),
    dismissed: false,
    implemented: false,
  },
  {
    id: 'rec_3',
    type: 'budget',
    title: 'Subscription Audit Recommended',
    description: 'You have 5 active subscriptions totaling $89.97/month. Some may be underutilized.',
    why: 'Subscription creep can silently drain your budget. A quick audit often reveals services you forgot about.',
    how: 'Review each subscription\'s usage in the past 30 days. Cancel any you haven\'t used in 2+ weeks.',
    expectedImpact: 'Potential savings of $20-40/month based on typical audit results.',
    risks: ['May lose access to services you occasionally use'],
    confidenceScore: 75,
    priority: 'medium',
    actionable: true,
    createdAt: new Date(),
    dismissed: false,
    implemented: false,
  },
];

// Sample Notifications
export const sampleNotifications: Notification[] = [
  {
    id: 'notif_1',
    type: 'alert',
    title: 'Budget Alert',
    message: 'You\'ve used 82% of your Shopping budget with 12 days left in the month.',
    priority: 'medium',
    read: false,
    actionUrl: '/budgets',
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif_2',
    type: 'reminder',
    title: 'Credit Card Payment Due',
    message: 'Your Capital One credit card payment of $75 is due in 3 days.',
    priority: 'high',
    read: false,
    actionUrl: '/debts',
    createdAt: new Date(now.getTime() - 5 * 60 * 60 * 1000),
  },
  {
    id: 'notif_3',
    type: 'achievement',
    title: 'Savings Milestone!',
    message: 'Congratulations! You\'ve saved $15,000 in your Emergency Fund.',
    priority: 'low',
    read: true,
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
  },
  {
    id: 'notif_4',
    type: 'insight',
    title: 'Spending Pattern Detected',
    message: 'Your coffee spending increased 40% this month compared to last month.',
    priority: 'low',
    read: true,
    actionUrl: '/transactions',
    createdAt: new Date(now.getTime() - 48 * 60 * 60 * 1000),
  },
];
